// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopQuanAo.Data;

#nullable disable

namespace ShopQuanAo.Migrations
{
    [DbContext(typeof(ShopQuanAoContext))]
    partial class ShopQuanAoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopQuanAo.Models.BienTheSanPham", b =>
                {
                    b.Property<int>("MaBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienThe"));

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaBienThe");

                    b.HasIndex("MaSP");

                    b.ToTable("BienTheSanPhams");
                });

            modelBuilder.Entity("ShopQuanAo.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .HasColumnType("int");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDH", "MaBienThe");

                    b.HasIndex("MaBienThe");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .HasColumnType("int");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGH", "MaBienThe");

                    b.HasIndex("MaBienThe");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSao")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDH")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaSP");

                    b.HasIndex("MaTK");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDM"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDM");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDTNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("TrangThaiDH")
                        .HasColumnType("int");

                    b.HasKey("MaDH");

                    b.HasIndex("MaTK");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.GiaoDichThanhToan", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<int>("MaDH")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDichDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiGiaoDich")
                        .HasColumnType("int");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaPT");

                    b.ToTable("GiaoDichThanhToans");
                });

            modelBuilder.Entity("ShopQuanAo.Models.GioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGH"));

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGH");

                    b.HasIndex("MaTK");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.KhachHang", b =>
                {
                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTK");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPT"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPT");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("ShopQuanAo.Models.QuanTriVien", b =>
                {
                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTK");

                    b.ToTable("QuanTriViens");
                });

            modelBuilder.Entity("ShopQuanAo.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnhChinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDM")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDM");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("ShopQuanAo.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuyenTruyCap")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaTK");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("ShopQuanAo.Models.BienTheSanPham", b =>
                {
                    b.HasOne("ShopQuanAo.Models.SanPham", "SanPham")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopQuanAo.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("ShopQuanAo.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("ShopQuanAo.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("ShopQuanAo.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DanhGia", b =>
                {
                    b.HasOne("ShopQuanAo.Models.DonHang", "DonHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DonHang", b =>
                {
                    b.HasOne("ShopQuanAo.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.GiaoDichThanhToan", b =>
                {
                    b.HasOne("ShopQuanAo.Models.DonHang", "DonHang")
                        .WithMany("GiaoDichThanhToans")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("GiaoDichThanhToans")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.GioHang", b =>
                {
                    b.HasOne("ShopQuanAo.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.KhachHang", b =>
                {
                    b.HasOne("ShopQuanAo.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("ShopQuanAo.Models.KhachHang", "MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.QuanTriVien", b =>
                {
                    b.HasOne("ShopQuanAo.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("QuanTriVien")
                        .HasForeignKey("ShopQuanAo.Models.QuanTriVien", "MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopQuanAo.Models.SanPham", b =>
                {
                    b.HasOne("ShopQuanAo.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ShopQuanAo.Models.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ShopQuanAo.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");

                    b.Navigation("GiaoDichThanhToans");
                });

            modelBuilder.Entity("ShopQuanAo.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("ShopQuanAo.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("GiaoDichThanhToans");
                });

            modelBuilder.Entity("ShopQuanAo.Models.SanPham", b =>
                {
                    b.Navigation("BienTheSanPhams");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("ShopQuanAo.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("KhachHang");

                    b.Navigation("QuanTriVien");
                });
#pragma warning restore 612, 618
        }
    }
}
